export { default as FeatureTable } from './featuretable-base'
export { default as B3dmFeatureTable } from './featuretable-b3dm'
export { default as I3dmFeatureTable } from './featuretable-i3dm'
export { default as PntsFeatureTable } from './featuretable-pnts'
export { default as VctrFeatureTable } from './featuretable-vctr'